/**
 * @file main.c
 * @author your name (you@domain.com)
 * @brief 
 * @version 0.1
 * @date 2022-05-18
 * 
 * @copyright Copyright (c) 2022
 * 
 */

#include <stdio.h>
#include "../Dialog/dialog.h"

#define DIALOGBOX_WIDTH                 (800)
#define DIALOGBOX_HEIGHT                (400)
#define DIALOGBOX_COLORBKGND            (0xFFA0A0A0)
#define DIALOGBOX_FONTFILESTR           ("../Resources/Fonts/arial.ttf")
#define DIALOGBOX_FONTSIZE              (30)

#define DIALOGBOX_CTRL_HRZSPACING       (5)

#define DIALOGBOX_LABEL_COLORBKGND      (0xFFF0F0F0)
#define DIALOGBOX_LABEL_WIDTH           (200)
#define DIALOGBOX_LABEL_HEIGHT          (25)
#define DIALOGBOX_LABEL_VERTSPACING     (10)
#define DIALOGBOX_LABEL_HRZSTART        (10)
#define DIALOGBOX_LABEL_VERTSTART       (10)

#define DIALOGBOX_LINEEDIT_WIDTH        (DIALOGBOX_WIDTH-DIALOGBOX_LABEL_WIDTH-2*DIALOGBOX_LABEL_HRZSTART-DIALOGBOX_CTRL_HRZSPACING)
#define DIALOGBOX_LINEEDIT_COLORBKGND   (0xFFD0D0D0)
#define DIALOGBOX_LINEEDIT_COLORTEXT    (0xFF202020)



int main(int argc, char**argv){

    (void)argc;
    (void)argv;
    
    printf("==============ENTER Dialogbox App===========\n");

    t_dialog*pDlgbox=DialogNew(
        "CMake Dialogbox App",
        DIALOGBOX_WIDTH,
        DIALOGBOX_HEIGHT,
        DIALOGBOX_COLORBKGND,
        DIALOGBOX_FONTFILESTR,
        DIALOGBOX_FONTSIZE);

    DialogAddNewControl(
        pDlgbox,
        CTRL_TYPE_LABEL,
        CTRL_FLAG_ENABLED | CTRL_FLAG_RIGHTJUSTIFIED | CTRL_FLAG_SHOWN, 
        1,
        DIALOGBOX_LABEL_HRZSTART,
        DIALOGBOX_LABEL_VERTSTART,
        DIALOGBOX_LABEL_WIDTH,
        DIALOGBOX_LABEL_HEIGHT,
        DIALOGBOX_COLORBKGND, 0xFF008000,
        "First name:");


    DialogAddNewControl(
        pDlgbox,
        CTRL_TYPE_LABEL,
        CTRL_FLAG_ENABLED | CTRL_FLAG_RIGHTJUSTIFIED | CTRL_FLAG_SHOWN, 
        2,
        DIALOGBOX_LABEL_HRZSTART,
        DIALOGBOX_LABEL_VERTSTART+DIALOGBOX_LABEL_HEIGHT+DIALOGBOX_LABEL_VERTSPACING,
        DIALOGBOX_LABEL_WIDTH,
        DIALOGBOX_LABEL_HEIGHT,
        DIALOGBOX_COLORBKGND, 0xFF000080,
        "Last name:");

    DialogAddNewControl(
        pDlgbox,
        CTRL_TYPE_LABEL,
        CTRL_FLAG_ENABLED | CTRL_FLAG_RIGHTJUSTIFIED | CTRL_FLAG_SHOWN, 
        3,
        DIALOGBOX_LABEL_HRZSTART,
        DIALOGBOX_LABEL_VERTSTART+2*(DIALOGBOX_LABEL_HEIGHT+DIALOGBOX_LABEL_VERTSPACING),
        DIALOGBOX_LABEL_WIDTH,
        DIALOGBOX_LABEL_HEIGHT,
        DIALOGBOX_COLORBKGND, 0xFF800000,
        "Pseudo:");

    DialogAddNewControl(
        pDlgbox,
        CTRL_TYPE_LABEL,
        CTRL_FLAG_ENABLED | CTRL_FLAG_RIGHTJUSTIFIED | CTRL_FLAG_SHOWN, 
        4,
        DIALOGBOX_LABEL_HRZSTART,
        DIALOGBOX_LABEL_VERTSTART+3*(DIALOGBOX_LABEL_HEIGHT+DIALOGBOX_LABEL_VERTSPACING),
        DIALOGBOX_LABEL_WIDTH,
        DIALOGBOX_LABEL_HEIGHT,
        DIALOGBOX_COLORBKGND, 0xFF88F8D8,
        "Mail:");

    DialogAddNewControl(
        pDlgbox,
        CTRL_TYPE_LABEL,
        CTRL_FLAG_ENABLED | CTRL_FLAG_RIGHTJUSTIFIED | CTRL_FLAG_SHOWN, 
        5,
        DIALOGBOX_LABEL_HRZSTART,
        DIALOGBOX_LABEL_VERTSTART+4*(DIALOGBOX_LABEL_HEIGHT+DIALOGBOX_LABEL_VERTSPACING),
        DIALOGBOX_LABEL_WIDTH,
        DIALOGBOX_LABEL_HEIGHT,
        DIALOGBOX_COLORBKGND, 0xFF0078A8,
        "Phone:");






    DialogAddNewControl(
        pDlgbox,
        CTRL_TYPE_LINEEDIT,
        CTRL_FLAG_ENABLED | CTRL_FLAG_LEFTJUSTIFIED | CTRL_FLAG_SHOWN | CTRL_FLAG_TABSTOPPED /*| CTRL_FLAG_FOCUSED*/, 
        11,
        DIALOGBOX_LABEL_HRZSTART + DIALOGBOX_LABEL_WIDTH + DIALOGBOX_CTRL_HRZSPACING,
        DIALOGBOX_LABEL_VERTSTART,
        DIALOGBOX_LINEEDIT_WIDTH,
        DIALOGBOX_LABEL_HEIGHT,
        DIALOGBOX_LINEEDIT_COLORBKGND,
        DIALOGBOX_LINEEDIT_COLORTEXT,
        "<your name>");

    DialogAddNewControl(
        pDlgbox,
        CTRL_TYPE_LINEEDIT,
        CTRL_FLAG_ENABLED | CTRL_FLAG_LEFTJUSTIFIED | CTRL_FLAG_SHOWN | CTRL_FLAG_TABSTOPPED, 
        12,
        DIALOGBOX_LABEL_HRZSTART + DIALOGBOX_LABEL_WIDTH + DIALOGBOX_CTRL_HRZSPACING,
         DIALOGBOX_LABEL_VERTSTART+DIALOGBOX_LABEL_HEIGHT+DIALOGBOX_LABEL_VERTSPACING,
        DIALOGBOX_LINEEDIT_WIDTH,
        DIALOGBOX_LABEL_HEIGHT,
        DIALOGBOX_LINEEDIT_COLORBKGND,
        DIALOGBOX_LINEEDIT_COLORTEXT,
        "<your last name>");

    DialogAddNewControl(
        pDlgbox,
        CTRL_TYPE_LINEEDIT,
        CTRL_FLAG_ENABLED | CTRL_FLAG_LEFTJUSTIFIED | CTRL_FLAG_SHOWN | CTRL_FLAG_TABSTOPPED | CTRL_FLAG_FOCUSED, 
        13,
        DIALOGBOX_LABEL_HRZSTART + DIALOGBOX_LABEL_WIDTH + DIALOGBOX_CTRL_HRZSPACING,
        DIALOGBOX_LABEL_VERTSTART+2*(DIALOGBOX_LABEL_HEIGHT+DIALOGBOX_LABEL_VERTSPACING),
        DIALOGBOX_LINEEDIT_WIDTH,
        DIALOGBOX_LABEL_HEIGHT,
        DIALOGBOX_LINEEDIT_COLORBKGND,
        DIALOGBOX_LINEEDIT_COLORTEXT,
        "<your pseudo>");

    DialogAddNewControl(
        pDlgbox,
        CTRL_TYPE_LINEEDIT,
        CTRL_FLAG_ENABLED | CTRL_FLAG_LEFTJUSTIFIED | CTRL_FLAG_SHOWN | CTRL_FLAG_TABSTOPPED, 
        14,
        DIALOGBOX_LABEL_HRZSTART + DIALOGBOX_LABEL_WIDTH + DIALOGBOX_CTRL_HRZSPACING,
        DIALOGBOX_LABEL_VERTSTART+3*(DIALOGBOX_LABEL_HEIGHT+DIALOGBOX_LABEL_VERTSPACING),
        DIALOGBOX_LINEEDIT_WIDTH,
        DIALOGBOX_LABEL_HEIGHT,
        DIALOGBOX_LINEEDIT_COLORBKGND,
        DIALOGBOX_LINEEDIT_COLORTEXT,
        "<your mail>");

    DialogAddNewControl(
        pDlgbox,
        CTRL_TYPE_LINEEDIT,
        CTRL_FLAG_ENABLED | CTRL_FLAG_LEFTJUSTIFIED | CTRL_FLAG_SHOWN | CTRL_FLAG_TABSTOPPED, 
        15,
        DIALOGBOX_LABEL_HRZSTART + DIALOGBOX_LABEL_WIDTH + DIALOGBOX_CTRL_HRZSPACING,
        DIALOGBOX_LABEL_VERTSTART+4*(DIALOGBOX_LABEL_HEIGHT+DIALOGBOX_LABEL_VERTSPACING),
        DIALOGBOX_LINEEDIT_WIDTH,
        DIALOGBOX_LABEL_HEIGHT,
        DIALOGBOX_LINEEDIT_COLORBKGND,
        DIALOGBOX_LINEEDIT_COLORTEXT,
        "<your phone number>");


    int res=DialogDoModal(pDlgbox);
    DialogDel(pDlgbox);

    printf("==============EXIT  Dialogbox App===========\n");

    return res;

}